/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistemaexperto;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;

/**
 *
 * @author Chass
 */
public class formularioSE extends javax.swing.JFrame {

    /**
     * Creates new form formularioSE
     */
    public formularioSE() {
        initComponents();
        setTitle("Sistema Experto de Diagnostico de Enfermedades");
        setResizable(false);
        this.setLocationRelativeTo(null);
        texto.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(223, 210, 36));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.gray));

        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel1.setText("Bienvenido al Sistema Experto");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Diagnostico de las 3 principales enfermedades en México");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemaexperto/seicono.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jLabel5.setText("Diabetes -Hipertensión - Insuficiencia renal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(28, 28, 28))
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(223, 210, 36));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.gray));

        jButton1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton1.setText("Empezar Diagnostico");
        jButton1.setToolTipText("Clic para comenzar el examen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        texto.setColumns(20);
        texto.setRows(5);
        jScrollPane1.setViewportView(texto);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Para comenzar el diagnostico dar clic");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("en el boton Empezar Diagnostico");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("responda todas las preguntas y");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("tendra un resultado en el recuadro blanco.");

        jButton2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton2.setText("Salir");
        jButton2.setToolTipText("Clic para salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
                        .addGap(3, 3, 3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(35, 35, 35)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int u,d,t,c,ci,se,u1,d1,t1,c1,ci1,se1,si1,oc1,u2,d2,t2,c2,ci2,se2;
        int dia = 0;
        int hip = 0;
        int ins = 0;
        
      u = JOptionPane.showConfirmDialog(rootPane, "¿Usted presenta fatiga regularmente?", null, YES_NO_OPTION);
      d = JOptionPane.showConfirmDialog(rootPane, "¿Realizas alguna actividad física regularmente?", null, YES_NO_OPTION);
      t = JOptionPane.showConfirmDialog(rootPane, "¿Sientes un aumento de apetito desmedido?", null, YES_NO_OPTION);
      c = JOptionPane.showConfirmDialog(rootPane, "¿Consideras que tienes una lenta recuperación de heridas?", null, YES_NO_OPTION);
      ci = JOptionPane.showConfirmDialog(rootPane, "¿Consumes muchos azucares?", null, YES_NO_OPTION);
      se = JOptionPane.showConfirmDialog(rootPane, "¿Padeces de visión borrosa?", null, YES_NO_OPTION);
      dia = u+d+t+c+ci+se;
      u1 = JOptionPane.showConfirmDialog(rootPane, "¿Presentas nauseas o mareos regularmente?", null, YES_NO_OPTION);
      d1 = JOptionPane.showConfirmDialog(rootPane, "¿Te zumban los oidos con frecuencia?", null, YES_NO_OPTION);
      t1 = JOptionPane.showConfirmDialog(rootPane, "¿Presentas regularmente dolor de pecho y/o lumbar?", null, YES_NO_OPTION);
      c1 = JOptionPane.showConfirmDialog(rootPane, "¿Presentas sangrado nasal constantemente?", null, YES_NO_OPTION);
      ci1 = JOptionPane.showConfirmDialog(rootPane, "¿Tienes estrés constantemente?", null, YES_NO_OPTION);
      se1 = JOptionPane.showConfirmDialog(rootPane, "¿Consumes alcohol y/o cigarro?", null, YES_NO_OPTION); 
      si1 = JOptionPane.showConfirmDialog(rootPane, "¿Te duele la cabeza regularmente?", null, YES_NO_OPTION);
      oc1 = JOptionPane.showConfirmDialog(rootPane, "¿Presentas calambres musculares con frecuencia?", null, YES_NO_OPTION);
      hip = u1+d1+t1+c1+ci1+se1+si1+oc1;
      u2 = JOptionPane.showConfirmDialog(rootPane, "¿Has presentado mareos sin razón últimamente?", null, YES_NO_OPTION);
      d2 = JOptionPane.showConfirmDialog(rootPane, "¿Presentas fatiga regularmente?", null, YES_NO_OPTION);
      t2 = JOptionPane.showConfirmDialog(rootPane, "¿Presentas nauseas o mareos regularmente?", null, YES_NO_OPTION);
      c2 = JOptionPane.showConfirmDialog(rootPane, "¿Has notado dificultad para respirar últimamente?", null, YES_NO_OPTION);
      ci2 = JOptionPane.showConfirmDialog(rootPane, "¿Presentas debilidad?", null, YES_NO_OPTION); 
      se2 = JOptionPane.showConfirmDialog(rootPane, "¿Tienes falta de apetito?", null, YES_NO_OPTION);
      ins = u2+d2+t2+c2+ci2+se2;
            if (( dia <= 2 ) && ( hip <= 3 ) && ( ins <= 2 ) ) { 
           String dg = "----------------------------------------------------\n"
                     + "-         Sistema Experto de diagnostico            \n"
                     + "- (Diabetes, Hipertension, insuficiencia renal)     \n"
                     + "----------------------------------------------------\n"
                     + "-                  DIAGNOSTICO                      \n"
                     + "----------------------------------------------------\n"
                     + "-     lo que probalemente usted presenta es         \n"
                     + "    DIABETES, HIPERTENCION E INSUFICIENCIA RENAL    \n"
                     + "Le recomendamos que se haga un estudio medico de estas enfermedades\n"
                     + "----------------------------------------------------";
           
           texto.setText(dg);
      }
      else if (( dia <= 2 ) && ( hip <= 3 )) { 
           String dg = "----------------------------------------------------\n"
                     + "-         Sistema Experto de diagnostico            \n"
                     + "- (Diabetes, Hipertension, insuficiencia renal)     \n"
                     + "----------------------------------------------------\n"
                     + "-                  DIAGNOSTICO                      \n"
                     + "----------------------------------------------------\n"
                     + "-     lo que probalemente usted presenta es         \n"
                     + "              DIABETES E HIPERTENCION               \n"
                     + "Le recomendamos que se haga un estudio medico de estas enfermedades\n"
                     + "----------------------------------------------------";
           
           texto.setText(dg);
      }
      else if (( dia <= 2 ) && ( ins <= 2 )) { 
           String dg = "----------------------------------------------------\n"
                     + "-         Sistema Experto de diagnostico            \n"
                     + "- (Diabetes, Hipertension, insuficiencia renal)     \n"
                     + "----------------------------------------------------\n"
                     + "-                  DIAGNOSTICO                      \n"
                     + "----------------------------------------------------\n"
                     + "-     lo que probalemente usted presenta es         \n"
                     + "          DIABETES E INSUFICIENCIA RENAL            \n"
                     + "Le recomendamos que se haga un estudio medico de estas enfermedades\n"
                     + "----------------------------------------------------";
           
           texto.setText(dg);
      } 
      else if (( ins <= 2 ) && ( hip <= 3 ) ) { 
           String dg = "----------------------------------------------------\n"
                     + "-         Sistema Experto de diagnostico            \n"
                     + "- (Diabetes, Hipertension, insuficiencia renal)     \n"
                     + "----------------------------------------------------\n"
                     + "-                  DIAGNOSTICO                      \n"
                     + "----------------------------------------------------\n"
                     + "-     lo que probalemente usted presenta es         \n"
                     + "        HIPERTENCION E INSUFICIENCIA RENAL          \n"
                     + "Le recomendamos que se haga un estudio medico de estas enfermedades\n"
                     + "----------------------------------------------------";
           
           texto.setText(dg);
          
      }
      else if ( dia <= 2 ) { 
           String dg = "----------------------------------------------------\n"
                     + "-         Sistema Experto de diagnostico            \n"
                     + "- (Diabetes, Hipertension, insuficiencia renal)     \n"
                     + "----------------------------------------------------\n"
                     + "-                  DIAGNOSTICO                      \n"
                     + "----------------------------------------------------\n"
                     + "-     lo que probalemente usted presenta es         \n"
                     + "                     DIABETES                       \n"
                     + "--Le recomendamos que se haga un estudio medico de esta enfermedad\n"
                     + "----------------------------------------------------";
           
           texto.setText(dg);
          
      }  else if ( hip <= 3 ) { 
           String dg = "----------------------------------------------------\n"
                     + "-         Sistema Experto de diagnostico            \n"
                     + "- (Diabetes, Hipertension, insuficiencia renal)     \n"
                     + "----------------------------------------------------\n"
                     + "-                  DIAGNOSTICO                      \n"
                     + "----------------------------------------------------\n"
                     + "-     lo que probalemente usted presenta es         \n"
                     + "                  HIPERTENCION                      \n"
                     + "--Le recomendamos que se haga un estudio medico de esta enfermedad\n"
                     + "----------------------------------------------------";
           
           texto.setText(dg);
          
      }  else if ( ins <= 2 ) { 
           String dg = "----------------------------------------------------\n"
                     + "-         Sistema Experto de diagnostico            \n"
                     + "- (Diabetes, Hipertension, insuficiencia renal)     \n"
                     + "----------------------------------------------------\n"
                     + "-                  DIAGNOSTICO                      \n"
                     + "----------------------------------------------------\n"
                     + "-     lo que probalemente usted presenta es         \n"
                     + "               INSUFICIENCIA RENAL                  \n"
                     + "--Le recomendamos que se haga un estudio medico de esta enfermedad\n"
                     + "----------------------------------------------------";
           
           texto.setText(dg);
          
      }  
      else { 
          String dg = "----------------------------------------------------\n"
                     + "-         Sistema Experto de diagnostico            \n"
                     + "- (Diabetes, Hipertension, insuficiencia renal)     \n"
                     + "----------------------------------------------------\n"
                     + "-                  DIAGNOSTICO                      \n"
                     + "----------------------------------------------------\n"
                     + "     Usted no presenta ninguna de las 3 enfermedades\n"
                     + "----------------------------------------------------";
                     texto.setText(dg);
      }
      

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    
    private void diabetes(){
      int u,d,t,c,ci,se;
      int sum = 0;
      int promd = 0;
     
      u = JOptionPane.showConfirmDialog(rootPane, "¿Usted presenta fatiga regularmente?", null, YES_NO_OPTION);
      d = JOptionPane.showConfirmDialog(rootPane, "¿No realizas alguna actividad física regularmente?", null, YES_NO_OPTION);
      t = JOptionPane.showConfirmDialog(rootPane, "¿Sientes un aumento de apetito desmedido?", null, YES_NO_OPTION);
      c = JOptionPane.showConfirmDialog(rootPane, "¿Consideras que tienes una lenta recuperación de heridas?", null, YES_NO_OPTION);
      ci = JOptionPane.showConfirmDialog(rootPane, "¿Consumes muchos azucares?", null, YES_NO_OPTION);
      se = JOptionPane.showConfirmDialog(rootPane, "¿Padeces de visión borrosa?", null, YES_NO_OPTION);
      
      sum = u+d+t+c+ci+se;
      
      if ( sum <= 2 ) { 
           String dg = "----------------------------------------------------\n"
                     + "-         Sistema Experto de diagnostico            \n"
                     + "- (Diabetes, Hipertension, insuficiencia renal)     \n"
                     + "----------------------------------------------------\n"
                     + "-                  DIAGNOSTICO                      \n"
                     + "----------------------------------------------------\n"
                     + "-  lo que probalemente usted presenta es DIABETES    \n"
                     + "--Le recomendamos que se haga un estudio medico de esta enfermedad\n"
                     + "----------------------------------------------------";
           
           texto.setText(dg);
      }
      else{ 

          hipertension();
      }
    }
    
    private void hipertension(){
      int u,d,t,c,ci,se,si,oc ; 
      int sum,prom;
      int promh=0;
      
      u = JOptionPane.showConfirmDialog(rootPane, "¿Presentas nauseas o mareos regularmente?", null, YES_NO_OPTION);
      d = JOptionPane.showConfirmDialog(rootPane, "¿Te zumban los oidos con frecuencia?", null, YES_NO_OPTION);
      t = JOptionPane.showConfirmDialog(rootPane, "¿Presentas regularmente dolor de pecho y/o lumbar?", null, YES_NO_OPTION);
      c = JOptionPane.showConfirmDialog(rootPane, "¿Presentas Sangrado nasal constantemente?", null, YES_NO_OPTION);
      ci = JOptionPane.showConfirmDialog(rootPane, "¿Tienes estrés constantemente?", null, YES_NO_OPTION);
      se = JOptionPane.showConfirmDialog(rootPane, "¿Consumes alcohol y/o cigarro?", null, YES_NO_OPTION); 
      si = JOptionPane.showConfirmDialog(rootPane, "¿Te duele la cabeza regularmente?", null, YES_NO_OPTION);
      oc = JOptionPane.showConfirmDialog(rootPane, "¿Presentas calambres musculares con frecuencia?", null, YES_NO_OPTION);
      
      if((u==0) && (d==0) && (t==0) && (c==0) && (ci==0) && (se==0) && (si==0) && (oc==0)){
           String dg = "----------------------------------------------------\n"
                     + "-         Sistema Experto de diagnostico            \n"
                     + "- (Diabetes, Hipertension, insuficiencia renal)     \n"
                     + "----------------------------------------------------\n"
                     + "-         DIAGNOSTICO                               \n"
                     + "----------------------------------------------------\n"
                     + "-       lo que usted presenta es HIPERTESION        \n"
                     + "--Le recomendamos que se haga un estudio medico de esta enfermedad\n"
                     + "----------------------------------------------------";
           
          texto.setText(dg);
      }
      else{
         sum = u+d+t+c+ci+se;
         prom = sum/6;
         prom = promh;
          insrenal();
      }
    }
    
    private void insrenal(){
       int u,d,t,c,ci,se;
       int sum, prom;
       int promins=0;
       
       u = JOptionPane.showConfirmDialog(rootPane, "¿Has presentado mareos sin razón últimamente?", null, YES_NO_OPTION);
       d = JOptionPane.showConfirmDialog(rootPane, "¿Presentas fatiga regularmente?", null, YES_NO_OPTION);
       t = JOptionPane.showConfirmDialog(rootPane, "¿Presentas nauseas o mareos regularmente?", null, YES_NO_OPTION);
       c = JOptionPane.showConfirmDialog(rootPane, "¿Has notado dificultad para respirar últimamente?", null, YES_NO_OPTION);
       ci = JOptionPane.showConfirmDialog(rootPane, "¿Presentas debilidad?", null, YES_NO_OPTION); 
       se = JOptionPane.showConfirmDialog(rootPane, "¿Tienes falta de apetito?", null, YES_NO_OPTION);
       
       if((u==0) && (d==0) && (t==0) && (c==0) && (ci==0) && (se==0)){
            String dg = "----------------------------------------------------\n"
                     + "-         Sistema Experto de diagnostico            \n"
                     + "-  (Diabetes, Hipertension, insuficiencia renal)    \n"
                     + "-----------------------------------------------------\n"
                     + "-                 DIAGNOSTICO                        \n"
                     + "-----------------------------------------------------\n"
                     + "-    lo que usted presenta es INSUFICIENCIA RENAL    \n"
                     + "--Le recomendamos que se haga un estudio medico de esta enfermedad\n"
                     + "-----------------------------------------------------";
            
           texto.setText(dg); 
       }
       else{
          sum = u+d+t+c+ci+se;
          prom = sum/6;
          prom = promins;
           diabetes();
       }
    }
    
    private void recomend(){
        
        int porc=0, numm;
        
        
        
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formularioSE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formularioSE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formularioSE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formularioSE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formularioSE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea texto;
    // End of variables declaration//GEN-END:variables
}
